export const TypeColor: Record<string, { bg: string; text: string }> = {
  normal: { bg: "bg-gray-400", text: "text-white" },
  fire: { bg: "bg-red-600", text: "text-white" },
  water: { bg: "bg-blue-600", text: "text-white" },
  electric: { bg: "bg-yellow-400", text: "text-white" },
  grass: { bg: "bg-green-400", text: "text-white" },
  ice: { bg: "bg-sky-400", text: "text-white" },
  fighting: { bg: "bg-orange-800", text: "text-white" },
  poison: { bg: "bg-fuchsia-800", text: "text-white" },
  ground: { bg: "bg-amber-900", text: "text-white" },
  flying: { bg: "bg-sky-400", text: "text-white" },
  psychic: { bg: "bg-purple-600", text: "text-white" },
  bug: { bg: "bg-emerald-500", text: "text-white" },
  rock: { bg: "bg-stone-600", text: "text-white" },
  ghost: { bg: "bg-fuchsia-900", text: "text-white" },
  dragon: { bg: "bg-teal-400", text: "text-white" },
  dark: { bg: "bg-violet-950", text: "text-white" },
  steel: { bg: "bg-slate-600", text: "text-white" },
  fairy: { bg: "bg-pink-500", text: "text-white" },
};
